// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynojeyofcxvhovxpcfai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlub2pleW9mY3h2aG92eHBjZmFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODU0NzUsImV4cCI6MjA2NDc2MTQ3NX0.BRe2i8MD-_32jZuq9fT0Ye-ijBRRsaqPRiSlu6hbvPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);